services:
  proxy:
    build: .
    ports:
      - "8010:8010"
    environment:
      - TRUNK=120M
      - SPLIT=1M
      - CONNS=3
      - HOST=0.0.0.0
      - PORT=8010
      - HEADERS={}
    restart: unless-stopped
